language: java
sudo: required
cache:
  directories:
    - "$HOME/.m2/repository"
jdk:
  - openjdk8
install: skip
script:
  - export PROJECT_NAME=QuickShop-Reremake #Set project name
  - git clone --depth=1 https://github.com/Ghost-chu/$PROJECT_NAME.git $PROJECT_NAME #Clone project
  - cd $PROJECT_NAME #Cd into project
  - mvn clean #Clean up
  - mvn -T 4 install #Install
after_success:
  - rm -rf push # GITHUB - CLEANUP
  #Script to release to Github Release
  - mkdir push
  - cp -r ./target/*.jar ./push/
  - rm -f ./push/original-*.jar
  - rm -f ./push/*-shaded.jar
  - rm -f ./push/*-sources.jar
  - mv -f ./push/*-javadoc.jar ./push/JavaDocument.zip
  #Script to release to Bukkit Dev
  - mkdir devbukkit
  - cp -r ./target/*.jar ./devbukkit/
  - rm -f ./devbukkit/original-*.jar
  - rm -f ./devbukkit/*-javadoc.jar
  - rm -f ./devbukkit/*-shaded.jar
  - rm -f ./devbukkit/*-sources.jar
  - rm -f ./target/original-*.jar
  - ls ./devbukkit -1 | grep ".jar$" > jarname.txt
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: xsJTi70QvH4lqKDhpJvqpfBBKSlxrTxkLofeJND58ZYPFhVk4egTalBYz/fT54s4G8YQHflSUNocl+W9zn/4lpdsdI1acMhCpBz014TJOMeEuwXN7yMslGO8eUKaZUiVjhygzrCp0RKwmY3TcpcFI98lbDAsVgFegzBdQpGk3gtlF3O/PAFEcHnhkEdohNJHlBrPFIdahnM8/saYbyzSzcjGRLkIOt75yzY/+AE0pQh24yI1K6xGA2FzO9LVBmNE15HvoqQhmZ8amKMbbsOJNe9OLJYHZRmWViudtaQibZtKWLLH+S+kjJ280PA96NtqCQ4xI/bDTfgxg34VWwKh3NtuAAS1mcnLpSTIQddI2D+R2pfG5igq69qXkK/Xedgv06H9y8dHw+ygBUm5J+cooktASw3WCgwncesU5oO5G2vd/NxbcpDSm5LookdpWtxHL36dg1gafPKJI2sthileN4LfIp9cBMgIN4bDdp9CLjzayzbVeRAqFrvbCV+qW5Eub5cMun0BEZpIEcAFnugMLrkMGm5wtLkFKwhE8Qy7ZmsArGOVFjaQloTWHhrae0avqbBbJPglbWeYT0Bm4M1fqNU80e8bwPaC24yJpTN+MoUZ4cvJ7c09++4b0Q4VK5ordyqipK0/2jalclGNRZAXkDr+dQO6vBCLYZPEjShW3nY=
  file:
    - ./push/*
  file_glob: true
  on:
    tags: true
  overwrite: true
after_deploy:
  #Confirm release to Bukkit Dev
  - chmod +x deploy.sh
  - "./deploy.sh $Curse_token"
  #Deploy to the mvn-repo
  - echo "Deploying to the Github..."
  - git clone --depth=1 https://$Github_token@github.com/Ghost-chu/maven-repo.git maven-repo
  - mvn deploy -DaltDeploymentRepository=mvn-repo::default::file:./maven-repo
  - cd maven-repo
  - git add .
  - git commit -m "Auto update by Travis-CI bot"
  - git push --force
  - cd ..
  - echo "Finish upload to Maven Repository"
#after_script:
#  #Upload data to BinaryRepository
#  - git clone --depth=1 https://$Github_token@github.com/Ghost-chu/BinaryRepository.git BinaryRepository
#  - mkdir -p ./BinaryRepository/$PROJECT_NAME/$TRAVIS_BUILD_NUMBER
#  - mkdir -p ./BinaryRepository/$PROJECT_NAME/$TRAVIS_BUILD_NUMBER/target
#  - cp -r ./target/* ./BinaryRepository/$PROJECT_NAME/$TRAVIS_BUILD_NUMBER/target
#  - echo -e "== Built by Travis-CI ==\nBuild Number [$TRAVIS_BUILD_NUMBER]\nBuild Type
#    [$TRAVIS_EVENT_TYPE]\nTag [$TRAVIS_TAG]\nCommit [$TRAVIS_COMMIT] - [$TRAVIS_COMMIT_MESSAGE]"
#    > ./BinaryRepository/$PROJECT_NAME/$TRAVIS_BUILD_NUMBER/BUILDINFO
#  - cd BinaryRepository
#  - git add .
#  - git commit -m "Auto update by Bot"
#  - git push --force
#  - cd .. #Back root
#  - echo "Finish upload to BinaryRepository"
