name: Update epics
on:
  issues:
    types: [opened, created, closed, reopened, deleted]
jobs:
  epics:
    runs-on: ubuntu-latest
    name: Update epic issues
    steps:
      - name: Run epics action
        uses: cloudaper/epics-action@v1
        with:
          github-token: ${{secrets.TOKEN}}
          epic-label-name: Feature
